#server:
#  port: 7777

# datasource config
spring:
  datasource:
    name: my-blog-datasource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_comic_city
    #    username: debian-sys-maint
    #    password: WPHacxVLrRYZsMAb
    username: root
    password: WTMSB12345+

# mybatis config
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# mybatis-plus config
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      # 配置MyBatis-Plus操作表的默认前缀
      table-prefix: t_
      # 配置MyBatis-Plus的主键策略
      id-type: auto

